# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_addr', models.CharField(max_length=50)),
                ('e_tel', models.CharField(max_length=11)),
                ('e_birth', models.DateField()),
                ('e_des', models.CharField(max_length=50)),
                ('s', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'db_table': 'extend',
            },
        ),
    ]
